//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWO.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWO.Shared.Resources.ViewResources", typeof(ViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcje.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wszystkie Wyniki Scenariuszy.
        /// </summary>
        public static string AllScoresAllScenarios {
            get {
                return ResourceManager.GetString("AllScoresAllScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średni Wynik.
        /// </summary>
        public static string AveragePercentage {
            get {
                return ResourceManager.GetString("AveragePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średni Wynik Scenariuszy.
        /// </summary>
        public static string AverageScenarioBar {
            get {
                return ResourceManager.GetString("AverageScenarioBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do listy.
        /// </summary>
        public static string BackList {
            get {
                return ResourceManager.GetString("BackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót do symulatora..
        /// </summary>
        public static string BackSimulator {
            get {
                return ResourceManager.GetString("BackSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykresy.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porównaj.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz Szkic Oceny.
        /// </summary>
        public static string CreateGradeTemplate {
            get {
                return ResourceManager.GetString("CreateGradeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz Lokację.
        /// </summary>
        public static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz nowy.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz Scenariusz.
        /// </summary>
        public static string CreateScenario {
            get {
                return ResourceManager.GetString("CreateScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz sensor..
        /// </summary>
        public static string CreateSensor {
            get {
                return ResourceManager.GetString("CreateSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz Symulator.
        /// </summary>
        public static string CreateSimulator {
            get {
                return ResourceManager.GetString("CreateSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz Użytkownika.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas usuwania, skontaktuj się z administratorem..
        /// </summary>
        public static string Delete_Failure {
            get {
                return ResourceManager.GetString("Delete_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś pewien usunięcia rekordu?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w edycji, sprawdź dane..
        /// </summary>
        public static string Edit_Failure {
            get {
                return ResourceManager.GetString("Edit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki Procentowe.
        /// </summary>
        public static string GradeInPercentage {
            get {
                return ResourceManager.GetString("GradeInPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oceny.
        /// </summary>
        public static string Grades {
            get {
                return ResourceManager.GetString("Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkic Oceny.
        /// </summary>
        public static string GradeTemplate {
            get {
                return ResourceManager.GetString("GradeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkice Ocen.
        /// </summary>
        public static string GradeTemplates {
            get {
                return ResourceManager.GetString("GradeTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główna.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Rekordów.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wczytaj z pliku .csv.
        /// </summary>
        public static string Load_Users {
            get {
                return ResourceManager.GetString("Load_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ładuję....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ośrodek.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagany wybór ośrodka..
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ośrodki.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie odnaleziono rekordów..
        /// </summary>
        public static string NoRecords {
            get {
                return ResourceManager.GetString("NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niewystarczająco placówek do utworzenia rekordu..
        /// </summary>
        public static string NotEnLocations {
            get {
                return ResourceManager.GetString("NotEnLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o padanym e-mailu nie istnieje..
        /// </summary>
        public static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieodnaleziono podanej strony..
        /// </summary>
        public static string Page404 {
            get {
                return ResourceManager.GetString("Page404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość rekordów na stronę:.
        /// </summary>
        public static string PageRecordCountLabel {
            get {
                return ResourceManager.GetString("PageRecordCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj losowe dane.
        /// </summary>
        public static string Populate {
            get {
                return ResourceManager.GetString("Populate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w rejestracji użytkownika, sprawdź dane..
        /// </summary>
        public static string Register_Failure {
            get {
                return ResourceManager.GetString("Register_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymagane.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenariusz.
        /// </summary>
        public static string Scenario {
            get {
                return ResourceManager.GetString("Scenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza Scenariuszy.
        /// </summary>
        public static string ScenarioAnalysis {
            get {
                return ResourceManager.GetString("ScenarioAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenariusze.
        /// </summary>
        public static string Scenarios {
            get {
                return ResourceManager.GetString("Scenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czujnik.
        /// </summary>
        public static string Sensor {
            get {
                return ResourceManager.GetString("Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czujniki.
        /// </summary>
        public static string Sensors {
            get {
                return ResourceManager.GetString("Sensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkolenie.
        /// </summary>
        public static string Simulation {
            get {
                return ResourceManager.GetString("Simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkolenia.
        /// </summary>
        public static string Simulations {
            get {
                return ResourceManager.GetString("Simulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symulator.
        /// </summary>
        public static string Simulator {
            get {
                return ResourceManager.GetString("Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symulatory.
        /// </summary>
        public static string Simulators {
            get {
                return ResourceManager.GetString("Simulators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porównanie czasu wykonania.
        /// </summary>
        public static string TimeComparisonChart {
            get {
                return ResourceManager.GetString("TimeComparisonChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkolony.
        /// </summary>
        public static string Trainee {
            get {
                return ResourceManager.GetString("Trainee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analiza Szkolonych.
        /// </summary>
        public static string TraineeAnalysis {
            get {
                return ResourceManager.GetString("TraineeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szkoleni.
        /// </summary>
        public static string Trainees {
            get {
                return ResourceManager.GetString("Trainees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualizuj.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaktualizowano pomyślnie..
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany email jest już zajęty..
        /// </summary>
        public static string User_Exists {
            get {
                return ResourceManager.GetString("User_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownicy.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź poprawny mail..
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne dane logowania..
        /// </summary>
        public static string Wrong_Credentials {
            get {
                return ResourceManager.GetString("Wrong_Credentials", resourceCulture);
            }
        }
    }
}
